import { tr } from "./locale-tag";
export type FormulaFunction = {
  name: string;
  category: string;
  signature: string;
  description: string;
  example: string;
  min: number;
  max: number;
};

const groups: [string, [string, string, string, string, number, number][]][] = [
  [
    "Logik und Eigenschaften",
    [
      [
        "prop",
        "prop(Eigenschaft)",
        "Liest eine Eigenschaft über ihren Namen oder ihre stabile ID.",
        'prop("Aufwand")',
        1,
        1,
      ],
      [
        "if",
        "if(Bedingung, Dann, Sonst)",
        "Wertet nur den gewählten Zweig aus.",
        'if(4 > 2, "Ja", "Nein")',
        3,
        3,
      ],
      [
        "ifs",
        "ifs(Bedingung, Wert, …, Standard)",
        "Verwendet den ersten zutreffenden Zweig, sonst den Standardwert.",
        "ifs(false, 1, true, 2, 0)",
        3,
        63,
      ],
      [
        "coalesce",
        "coalesce(Wert, …)",
        "Liefert den ersten Wert, der weder null noch leerer Text ist.",
        'coalesce("", 0, 10)',
        1,
        64,
      ],
      [
        "and",
        "and(Bedingung, …)",
        "Alle Bedingungen müssen wahr sein. Bricht beim ersten falschen Wert ab.",
        "and(true, 3 > 2)",
        2,
        64,
      ],
      [
        "or",
        "or(Bedingung, …)",
        "Mindestens eine Bedingung muss wahr sein. Bricht beim ersten wahren Wert ab.",
        "or(false, true)",
        2,
        64,
      ],
      [
        "not",
        "not(Bedingung)",
        "Kehrt einen Wahrheitswert um.",
        "not(false)",
        1,
        1,
      ],
    ],
  ],
  [
    "Zahlen",
    [
      [
        "sum",
        "sum(Zahl oder Liste, …)",
        "Addiert Zahlen. Leere Werte zählen als null.",
        "sum(1, list(2, 3))",
        0,
        64,
      ],
      [
        "min",
        "min(Zahl oder Liste, …)",
        "Kleinster Zahlenwert.",
        "min(3, 1, 2)",
        1,
        64,
      ],
      [
        "max",
        "max(Zahl oder Liste, …)",
        "Größter Zahlenwert.",
        "max(3, 1, 2)",
        1,
        64,
      ],
      [
        "average",
        "average(Zahl oder Liste, …)",
        "Arithmetischer Mittelwert.",
        "average(2, 4, 6)",
        1,
        64,
      ],
      [
        "round",
        "round(Zahl, Stellen?)",
        "Rundet auf null bis zehn Nachkommastellen.",
        "round(10 / 3, 2)",
        1,
        2,
      ],
      ["abs", "abs(Zahl)", "Absoluter Betrag.", "abs(-4)", 1, 1],
      [
        "ceil",
        "ceil(Zahl)",
        "Rundet zur nächstgrößeren ganzen Zahl.",
        "ceil(2.1)",
        1,
        1,
      ],
      [
        "floor",
        "floor(Zahl)",
        "Rundet zur nächstkleineren ganzen Zahl.",
        "floor(2.9)",
        1,
        1,
      ],
      [
        "sqrt",
        "sqrt(Zahl)",
        "Quadratwurzel einer nicht negativen Zahl.",
        "sqrt(9)",
        1,
        1,
      ],
      [
        "pow",
        "pow(Basis, Exponent)",
        "Potenziert eine Zahl.",
        "pow(2, 3)",
        2,
        2,
      ],
      [
        "mod",
        "mod(Zahl, Divisor)",
        "Rest der Division, mit dem Vorzeichen der ersten Zahl.",
        "mod(10, 3)",
        2,
        2,
      ],
      ["sign", "sign(Zahl)", "Liefert -1, 0 oder 1.", "sign(-3)", 1, 1],
    ],
  ],
  [
    "Text",
    [
      [
        "concat",
        "concat(Wert, …)",
        "Verbindet Werte zu Text.",
        'concat("Hallo ", "Welt")',
        0,
        64,
      ],
      [
        "length",
        "length(Wert)",
        "Länge der Textdarstellung in UTF-16-Zeichen. Für Listenelemente count verwenden.",
        'length("Plan")',
        1,
        1,
      ],
      [
        "lower",
        "lower(Text)",
        "Wandelt in Kleinbuchstaben um.",
        'lower("PLAN")',
        1,
        1,
      ],
      [
        "upper",
        "upper(Text)",
        "Wandelt in Großbuchstaben um.",
        'upper("Plan")',
        1,
        1,
      ],
      [
        "empty",
        "empty(Wert)",
        "Prüft auf eine leere Textdarstellung; null und leere Listen gelten als leer.",
        'empty("")',
        1,
        1,
      ],
      [
        "contains",
        "contains(Wert, Suchtext)",
        "Sucht in der Textdarstellung nach einem Teiltext.",
        'contains("Flowplan", "plan")',
        2,
        2,
      ],
      [
        "trim",
        "trim(Text)",
        "Entfernt Leerraum am Anfang und Ende.",
        'trim("  Plan  ")',
        1,
        1,
      ],
      [
        "slice",
        "slice(Text, Beginn, Ende?)",
        "Teiltext; Positionen beginnen bei null, negative Positionen zählen vom Ende.",
        'slice("Flowplan", 4)',
        2,
        3,
      ],
      [
        "replace",
        "replace(Text, Suche, Ersatz)",
        "Ersetzt das erste wörtliche Vorkommen, ohne reguläre Ausdrücke.",
        'replace("a-a", "a", "b")',
        3,
        3,
      ],
      [
        "replaceAll",
        "replaceAll(Text, Suche, Ersatz)",
        "Ersetzt alle wörtlichen Vorkommen. Der Suchtext darf nicht leer sein.",
        'replaceAll("a-a", "a", "b")',
        3,
        3,
      ],
      [
        "startsWith",
        "startsWith(Text, Anfang)",
        "Prüft den Textanfang.",
        'startsWith("Flowplan", "Flow")',
        2,
        2,
      ],
      [
        "endsWith",
        "endsWith(Text, Ende)",
        "Prüft das Textende.",
        'endsWith("Flowplan", "plan")',
        2,
        2,
      ],
      [
        "repeat",
        "repeat(Text, Anzahl)",
        "Wiederholt Text; das Ergebnis ist auf 20.000 Zeichen begrenzt.",
        'repeat("•", 3)',
        2,
        2,
      ],
      [
        "format",
        "format(Wert)",
        "Wandelt einen Wert in Text um.",
        "format(42)",
        1,
        1,
      ],
      [
        "toNumber",
        "toNumber(Wert)",
        "Wandelt Zahlen, numerischen Text und Wahrheitswerte in eine Zahl um.",
        'toNumber("12.5")',
        1,
        1,
      ],
    ],
  ],
  [
    "Listen",
    [
      [
        "list",
        "list(Wert, …)",
        "Erstellt eine Liste.",
        'list("A", "B")',
        0,
        64,
      ],
      [
        "count",
        "count(Liste)",
        "Zählt die Elemente einer Liste.",
        'count(list("A", "B"))',
        1,
        1,
      ],
      [
        "at",
        "at(Liste, Position)",
        "Liest ein Element; nullbasiert, negative Positionen zählen vom Ende. Außerhalb der Liste: null.",
        "at(list(10, 20), 1)",
        2,
        2,
      ],
      [
        "first",
        "first(Liste)",
        "Erstes Element oder null bei leerer Liste.",
        "first(list(10, 20))",
        1,
        1,
      ],
      [
        "last",
        "last(Liste)",
        "Letztes Element oder null bei leerer Liste.",
        "last(list(10, 20))",
        1,
        1,
      ],
      [
        "join",
        "join(Liste, Trennzeichen?)",
        "Verbindet Listenelemente zu Text.",
        'join(list("A", "B"), " / ")',
        1,
        2,
      ],
      [
        "split",
        "split(Text, Trennzeichen)",
        "Teilt Text in höchstens 1.000 Listenelemente.",
        'split("A,B", ",")',
        2,
        2,
      ],
      [
        "unique",
        "unique(Liste)",
        "Entfernt doppelte Werte bei gleicher JSON-Darstellung.",
        "unique(list(1, 1, 2))",
        1,
        1,
      ],
      [
        "sort",
        "sort(Liste)",
        "Sortiert Zahlen numerisch, andere Werte nach ihrer deutschen Textdarstellung.",
        "sort(list(3, 1, 2))",
        1,
        1,
      ],
      [
        "reverse",
        "reverse(Liste)",
        "Kehrt die Reihenfolge um.",
        "reverse(list(1, 2, 3))",
        1,
        1,
      ],
    ],
  ],
  [
    "Datum und Uhrzeit",
    [
      ["now", "now()", "Aktueller Zeitpunkt in UTC.", "now()", 0, 0],
      [
        "today",
        "today(Zeitzone?)",
        "Heutiges Datum; ohne Zeitzone gilt UTC.",
        'today("Europe/Berlin")',
        0,
        1,
      ],
      [
        "parseDate",
        "parseDate(ISO-Text)",
        "Prüft ein ISO-Datum oder einen Zeitpunkt. Uhrzeiten ohne Offset gelten als UTC.",
        'parseDate("2026-09-23")',
        1,
        1,
      ],
      [
        "formatDate",
        "formatDate(Datum, Format?, Zeitzone?)",
        "Formatiert YYYY, MM, DD, HH, mm und ss. Standard: YYYY-MM-DD und UTC.",
        'formatDate("2026-09-23", "DD.MM.YYYY")',
        1,
        3,
      ],
      [
        "dateAdd",
        "dateAdd(Datum, Anzahl, Einheit, Zeitzone?)",
        "Addiert years, months, weeks, days, hours, minutes oder seconds. Kalendereinheiten beachten die Zeitzone; Standard UTC.",
        'dateAdd("2026-09-23", 2, "days")',
        3,
        4,
      ],
      [
        "dateSubtract",
        "dateSubtract(Datum, Anzahl, Einheit, Zeitzone?)",
        "Zieht Datumseinheiten ab; Standardzeitzone UTC.",
        'dateSubtract("2026-09-23", 2, "days")',
        3,
        4,
      ],
      [
        "dateBetween",
        "dateBetween(Ende, Beginn, Einheit?)",
        "Differenz. Ohne Einheit gerundete Tage wie bisher; mit Einheit vollständige Einheiten, Monats-/Jahresdifferenzen in UTC.",
        'dateBetween("2026-09-25", "2026-09-23", "days")',
        2,
        3,
      ],
      [
        "year",
        "year(Datum, Zeitzone?)",
        "Jahreszahl, standardmäßig in UTC.",
        'year("2026-09-23")',
        1,
        2,
      ],
      [
        "month",
        "month(Datum, Zeitzone?)",
        "Monat von 1 bis 12, standardmäßig in UTC.",
        'month("2026-09-23")',
        1,
        2,
      ],
      [
        "day",
        "day(Datum, Zeitzone?)",
        "Tag des Monats, standardmäßig in UTC.",
        'day("2026-09-23")',
        1,
        2,
      ],
      [
        "hour",
        "hour(Datum, Zeitzone?)",
        "Stunde von 0 bis 23, standardmäßig in UTC.",
        'hour("2026-09-23T09:30:00Z")',
        1,
        2,
      ],
      [
        "minute",
        "minute(Datum, Zeitzone?)",
        "Minute von 0 bis 59, standardmäßig in UTC.",
        'minute("2026-09-23T09:30:00Z")',
        1,
        2,
      ],
      [
        "timestamp",
        "timestamp(Datum)",
        "Millisekunden seit dem Unix-Epoch; Datum ohne Uhrzeit wird UTC-Mitternacht.",
        'timestamp("1970-01-01")',
        1,
        1,
      ],
      [
        "fromTimestamp",
        "fromTimestamp(Millisekunden)",
        "Wandelt Unix-Millisekunden in einen UTC-Zeitpunkt um.",
        "fromTimestamp(0)",
        1,
        1,
      ],
    ],
  ],
];

// English names, descriptions and examples (the browser shows them for English readers).
const english: Record<string, [string, string, string?]> = {
  abs: ["abs(number)", "Absolute value."],
  sign: ["sign(number)", "Returns -1, 0 or 1."],
  now: ["now()", "Current point in time in UTC."],
  prop: ["prop(property)", "Reads a property by its name or its stable ID.", "prop(\"Effort\")"],
  if: ["if(condition, then, else)", "Evaluates only the chosen branch.", "if(4 > 2, \"Yes\", \"No\")"],
  ifs: ["ifs(condition, value, \u2026, default)", "Uses the first matching branch, otherwise the default value."],
  coalesce: ["coalesce(value, \u2026)", "Returns the first value that is neither null nor empty text."],
  and: ["and(condition, \u2026)", "All conditions must be true. Stops at the first false value."],
  or: ["or(condition, \u2026)", "At least one condition must be true. Stops at the first true value."],
  not: ["not(condition)", "Inverts a truth value."],
  sum: ["sum(number or list, \u2026)", "Adds numbers. Empty values count as zero."],
  min: ["min(number or list, \u2026)", "Smallest number."],
  max: ["max(number or list, \u2026)", "Largest number."],
  average: ["average(number or list, \u2026)", "Arithmetic mean."],
  round: ["round(number, places?)", "Rounds to zero to ten decimal places."],
  ceil: ["ceil(number)", "Rounds up to the next whole number."],
  floor: ["floor(number)", "Rounds down to the next whole number."],
  sqrt: ["sqrt(number)", "Square root of a non-negative number."],
  pow: ["pow(base, exponent)", "Raises a number to a power."],
  mod: ["mod(number, divisor)", "Remainder of the division, with the sign of the first number."],
  concat: ["concat(value, \u2026)", "Joins values into text.", "concat(\"Hello \", \"world\")"],
  length: ["length(value)", "Length of the text form in UTF-16 characters. Use count for list items."],
  lower: ["lower(text)", "Converts to lower case."],
  upper: ["upper(text)", "Converts to upper case."],
  empty: ["empty(value)", "Checks for an empty text form; null and empty lists count as empty."],
  contains: ["contains(value, search)", "Looks for a piece of text in the text form."],
  trim: ["trim(text)", "Removes white space at the start and end."],
  slice: ["slice(text, start, end?)", "Part of the text; positions start at zero, negative positions count from the end."],
  replace: ["replace(text, search, replacement)", "Replaces the first literal occurrence, without regular expressions."],
  replaceAll: ["replaceAll(text, search, replacement)", "Replaces all literal occurrences. The search text must not be empty."],
  startsWith: ["startsWith(text, start)", "Checks the start of the text."],
  endsWith: ["endsWith(text, end)", "Checks the end of the text."],
  repeat: ["repeat(text, count)", "Repeats text; the result is limited to 20,000 characters."],
  format: ["format(value)", "Converts a value to text."],
  toNumber: ["toNumber(value)", "Converts numbers, numeric text and truth values to a number."],
  list: ["list(value, \u2026)", "Creates a list."],
  count: ["count(list)", "Counts the items of a list."],
  at: ["at(list, position)", "Reads an item; zero-based, negative positions count from the end. Outside the list: null."],
  first: ["first(list)", "First item, or null for an empty list."],
  last: ["last(list)", "Last item, or null for an empty list."],
  join: ["join(list, separator?)", "Joins list items into text."],
  split: ["split(text, separator)", "Splits text into at most 1,000 list items."],
  unique: ["unique(list)", "Removes duplicate values with the same JSON form."],
  sort: ["sort(list)", "Sorts numbers numerically, other values by their German text form."],
  reverse: ["reverse(list)", "Reverses the order."],
  today: ["today(time zone?)", "Today's date; without a time zone UTC applies."],
  parseDate: ["parseDate(ISO text)", "Checks an ISO date or timestamp. Times without an offset count as UTC."],
  formatDate: ["formatDate(date, format?, time zone?)", "Formats YYYY, MM, DD, HH, mm and ss. Default: YYYY-MM-DD and UTC."],
  dateAdd: ["dateAdd(date, amount, unit, time zone?)", "Adds years, months, weeks, days, hours, minutes or seconds. Calendar units respect the time zone; default UTC."],
  dateSubtract: ["dateSubtract(date, amount, unit, time zone?)", "Subtracts date units; default time zone UTC."],
  dateBetween: ["dateBetween(end, start, unit?)", "Difference. Without a unit, rounded days as before; with a unit, whole units, month and year differences in UTC."],
  year: ["year(date, time zone?)", "Year, in UTC by default."],
  month: ["month(date, time zone?)", "Month from 1 to 12, in UTC by default."],
  day: ["day(date, time zone?)", "Day of the month, in UTC by default."],
  hour: ["hour(date, time zone?)", "Hour from 0 to 23, in UTC by default."],
  minute: ["minute(date, time zone?)", "Minute from 0 to 59, in UTC by default."],
  timestamp: ["timestamp(date)", "Milliseconds since the Unix epoch; a date without a time becomes UTC midnight."],
  fromTimestamp: ["fromTimestamp(milliseconds)", "Converts Unix milliseconds to a UTC point in time."],
};
const categories: Record<string, string> = {
  "Logik und Eigenschaften": "Logic and properties",
  "Zahlen": "Numbers",
  "Text": "Text",
  "Listen": "Lists",
  "Datum und Uhrzeit": "Date and time",
};
export const formulaFunctions: FormulaFunction[] = groups.flatMap(
  ([category, entries]) =>
    entries.map(([name, signature, description, example, min, max]) => ({
      name,
      category: tr(category, categories[category]),
      signature: tr(signature, english[name][0]),
      description: tr(description, english[name][1]),
      example: tr(example, english[name][2] ?? example),
      min,
      max,
    })),
);
export const formulaFunctionByName = new Map(
  formulaFunctions.map((entry) => [entry.name.toLowerCase(), entry]),
);
