export type FormulaFunction = {
  name: string;
  category: string;
  signature: string;
  description: string;
  example: string;
  min: number;
  max: number;
};

const groups: [string, [string, string, string, string, number, number][]][] = [
  [
    "Logik und Eigenschaften",
    [
      [
        "prop",
        "prop(Eigenschaft)",
        "Liest eine Eigenschaft über ihren Namen oder ihre stabile ID.",
        'prop("Aufwand")',
        1,
        1,
      ],
      [
        "if",
        "if(Bedingung, Dann, Sonst)",
        "Wertet nur den gewählten Zweig aus.",
        'if(4 > 2, "Ja", "Nein")',
        3,
        3,
      ],
      [
        "ifs",
        "ifs(Bedingung, Wert, …, Standard)",
        "Verwendet den ersten zutreffenden Zweig, sonst den Standardwert.",
        "ifs(false, 1, true, 2, 0)",
        3,
        63,
      ],
      [
        "coalesce",
        "coalesce(Wert, …)",
        "Liefert den ersten Wert, der weder null noch leerer Text ist.",
        'coalesce("", 0, 10)',
        1,
        64,
      ],
      [
        "and",
        "and(Bedingung, …)",
        "Alle Bedingungen müssen wahr sein. Bricht beim ersten falschen Wert ab.",
        "and(true, 3 > 2)",
        2,
        64,
      ],
      [
        "or",
        "or(Bedingung, …)",
        "Mindestens eine Bedingung muss wahr sein. Bricht beim ersten wahren Wert ab.",
        "or(false, true)",
        2,
        64,
      ],
      [
        "not",
        "not(Bedingung)",
        "Kehrt einen Wahrheitswert um.",
        "not(false)",
        1,
        1,
      ],
    ],
  ],
  [
    "Zahlen",
    [
      [
        "sum",
        "sum(Zahl oder Liste, …)",
        "Addiert Zahlen. Leere Werte zählen als null.",
        "sum(1, list(2, 3))",
        0,
        64,
      ],
      [
        "min",
        "min(Zahl oder Liste, …)",
        "Kleinster Zahlenwert.",
        "min(3, 1, 2)",
        1,
        64,
      ],
      [
        "max",
        "max(Zahl oder Liste, …)",
        "Größter Zahlenwert.",
        "max(3, 1, 2)",
        1,
        64,
      ],
      [
        "average",
        "average(Zahl oder Liste, …)",
        "Arithmetischer Mittelwert.",
        "average(2, 4, 6)",
        1,
        64,
      ],
      [
        "round",
        "round(Zahl, Stellen?)",
        "Rundet auf null bis zehn Nachkommastellen.",
        "round(10 / 3, 2)",
        1,
        2,
      ],
      ["abs", "abs(Zahl)", "Absoluter Betrag.", "abs(-4)", 1, 1],
      [
        "ceil",
        "ceil(Zahl)",
        "Rundet zur nächstgrößeren ganzen Zahl.",
        "ceil(2.1)",
        1,
        1,
      ],
      [
        "floor",
        "floor(Zahl)",
        "Rundet zur nächstkleineren ganzen Zahl.",
        "floor(2.9)",
        1,
        1,
      ],
      [
        "sqrt",
        "sqrt(Zahl)",
        "Quadratwurzel einer nicht negativen Zahl.",
        "sqrt(9)",
        1,
        1,
      ],
      [
        "pow",
        "pow(Basis, Exponent)",
        "Potenziert eine Zahl.",
        "pow(2, 3)",
        2,
        2,
      ],
      [
        "mod",
        "mod(Zahl, Divisor)",
        "Rest der Division, mit dem Vorzeichen der ersten Zahl.",
        "mod(10, 3)",
        2,
        2,
      ],
      ["sign", "sign(Zahl)", "Liefert -1, 0 oder 1.", "sign(-3)", 1, 1],
    ],
  ],
  [
    "Text",
    [
      [
        "concat",
        "concat(Wert, …)",
        "Verbindet Werte zu Text.",
        'concat("Hallo ", "Welt")',
        0,
        64,
      ],
      [
        "length",
        "length(Wert)",
        "Länge der Textdarstellung in UTF-16-Zeichen. Für Listenelemente count verwenden.",
        'length("Plan")',
        1,
        1,
      ],
      [
        "lower",
        "lower(Text)",
        "Wandelt in Kleinbuchstaben um.",
        'lower("PLAN")',
        1,
        1,
      ],
      [
        "upper",
        "upper(Text)",
        "Wandelt in Großbuchstaben um.",
        'upper("Plan")',
        1,
        1,
      ],
      [
        "empty",
        "empty(Wert)",
        "Prüft auf eine leere Textdarstellung; null und leere Listen gelten als leer.",
        'empty("")',
        1,
        1,
      ],
      [
        "contains",
        "contains(Wert, Suchtext)",
        "Sucht in der Textdarstellung nach einem Teiltext.",
        'contains("Flowplan", "plan")',
        2,
        2,
      ],
      [
        "trim",
        "trim(Text)",
        "Entfernt Leerraum am Anfang und Ende.",
        'trim("  Plan  ")',
        1,
        1,
      ],
      [
        "slice",
        "slice(Text, Beginn, Ende?)",
        "Teiltext; Positionen beginnen bei null, negative Positionen zählen vom Ende.",
        'slice("Flowplan", 4)',
        2,
        3,
      ],
      [
        "replace",
        "replace(Text, Suche, Ersatz)",
        "Ersetzt das erste wörtliche Vorkommen, ohne reguläre Ausdrücke.",
        'replace("a-a", "a", "b")',
        3,
        3,
      ],
      [
        "replaceAll",
        "replaceAll(Text, Suche, Ersatz)",
        "Ersetzt alle wörtlichen Vorkommen. Der Suchtext darf nicht leer sein.",
        'replaceAll("a-a", "a", "b")',
        3,
        3,
      ],
      [
        "startsWith",
        "startsWith(Text, Anfang)",
        "Prüft den Textanfang.",
        'startsWith("Flowplan", "Flow")',
        2,
        2,
      ],
      [
        "endsWith",
        "endsWith(Text, Ende)",
        "Prüft das Textende.",
        'endsWith("Flowplan", "plan")',
        2,
        2,
      ],
      [
        "repeat",
        "repeat(Text, Anzahl)",
        "Wiederholt Text; das Ergebnis ist auf 20.000 Zeichen begrenzt.",
        'repeat("•", 3)',
        2,
        2,
      ],
      [
        "format",
        "format(Wert)",
        "Wandelt einen Wert in Text um.",
        "format(42)",
        1,
        1,
      ],
      [
        "toNumber",
        "toNumber(Wert)",
        "Wandelt Zahlen, numerischen Text und Wahrheitswerte in eine Zahl um.",
        'toNumber("12.5")',
        1,
        1,
      ],
    ],
  ],
  [
    "Listen",
    [
      [
        "list",
        "list(Wert, …)",
        "Erstellt eine Liste.",
        'list("A", "B")',
        0,
        64,
      ],
      [
        "count",
        "count(Liste)",
        "Zählt die Elemente einer Liste.",
        'count(list("A", "B"))',
        1,
        1,
      ],
      [
        "at",
        "at(Liste, Position)",
        "Liest ein Element; nullbasiert, negative Positionen zählen vom Ende. Außerhalb der Liste: null.",
        "at(list(10, 20), 1)",
        2,
        2,
      ],
      [
        "first",
        "first(Liste)",
        "Erstes Element oder null bei leerer Liste.",
        "first(list(10, 20))",
        1,
        1,
      ],
      [
        "last",
        "last(Liste)",
        "Letztes Element oder null bei leerer Liste.",
        "last(list(10, 20))",
        1,
        1,
      ],
      [
        "join",
        "join(Liste, Trennzeichen?)",
        "Verbindet Listenelemente zu Text.",
        'join(list("A", "B"), " / ")',
        1,
        2,
      ],
      [
        "split",
        "split(Text, Trennzeichen)",
        "Teilt Text in höchstens 1.000 Listenelemente.",
        'split("A,B", ",")',
        2,
        2,
      ],
      [
        "unique",
        "unique(Liste)",
        "Entfernt doppelte Werte bei gleicher JSON-Darstellung.",
        "unique(list(1, 1, 2))",
        1,
        1,
      ],
      [
        "sort",
        "sort(Liste)",
        "Sortiert Zahlen numerisch, andere Werte nach ihrer deutschen Textdarstellung.",
        "sort(list(3, 1, 2))",
        1,
        1,
      ],
      [
        "reverse",
        "reverse(Liste)",
        "Kehrt die Reihenfolge um.",
        "reverse(list(1, 2, 3))",
        1,
        1,
      ],
    ],
  ],
  [
    "Datum und Uhrzeit",
    [
      ["now", "now()", "Aktueller Zeitpunkt in UTC.", "now()", 0, 0],
      [
        "today",
        "today(Zeitzone?)",
        "Heutiges Datum; ohne Zeitzone gilt UTC.",
        'today("Europe/Berlin")',
        0,
        1,
      ],
      [
        "parseDate",
        "parseDate(ISO-Text)",
        "Prüft ein ISO-Datum oder einen Zeitpunkt. Uhrzeiten ohne Offset gelten als UTC.",
        'parseDate("2026-09-23")',
        1,
        1,
      ],
      [
        "formatDate",
        "formatDate(Datum, Format?, Zeitzone?)",
        "Formatiert YYYY, MM, DD, HH, mm und ss. Standard: YYYY-MM-DD und UTC.",
        'formatDate("2026-09-23", "DD.MM.YYYY")',
        1,
        3,
      ],
      [
        "dateAdd",
        "dateAdd(Datum, Anzahl, Einheit, Zeitzone?)",
        "Addiert years, months, weeks, days, hours, minutes oder seconds. Kalendereinheiten beachten die Zeitzone; Standard UTC.",
        'dateAdd("2026-09-23", 2, "days")',
        3,
        4,
      ],
      [
        "dateSubtract",
        "dateSubtract(Datum, Anzahl, Einheit, Zeitzone?)",
        "Zieht Datumseinheiten ab; Standardzeitzone UTC.",
        'dateSubtract("2026-09-23", 2, "days")',
        3,
        4,
      ],
      [
        "dateBetween",
        "dateBetween(Ende, Beginn, Einheit?)",
        "Differenz. Ohne Einheit gerundete Tage wie bisher; mit Einheit vollständige Einheiten, Monats-/Jahresdifferenzen in UTC.",
        'dateBetween("2026-09-25", "2026-09-23", "days")',
        2,
        3,
      ],
      [
        "year",
        "year(Datum, Zeitzone?)",
        "Jahreszahl, standardmäßig in UTC.",
        'year("2026-09-23")',
        1,
        2,
      ],
      [
        "month",
        "month(Datum, Zeitzone?)",
        "Monat von 1 bis 12, standardmäßig in UTC.",
        'month("2026-09-23")',
        1,
        2,
      ],
      [
        "day",
        "day(Datum, Zeitzone?)",
        "Tag des Monats, standardmäßig in UTC.",
        'day("2026-09-23")',
        1,
        2,
      ],
      [
        "hour",
        "hour(Datum, Zeitzone?)",
        "Stunde von 0 bis 23, standardmäßig in UTC.",
        'hour("2026-09-23T09:30:00Z")',
        1,
        2,
      ],
      [
        "minute",
        "minute(Datum, Zeitzone?)",
        "Minute von 0 bis 59, standardmäßig in UTC.",
        'minute("2026-09-23T09:30:00Z")',
        1,
        2,
      ],
      [
        "timestamp",
        "timestamp(Datum)",
        "Millisekunden seit dem Unix-Epoch; Datum ohne Uhrzeit wird UTC-Mitternacht.",
        'timestamp("1970-01-01")',
        1,
        1,
      ],
      [
        "fromTimestamp",
        "fromTimestamp(Millisekunden)",
        "Wandelt Unix-Millisekunden in einen UTC-Zeitpunkt um.",
        "fromTimestamp(0)",
        1,
        1,
      ],
    ],
  ],
];

export const formulaFunctions: FormulaFunction[] = groups.flatMap(
  ([category, entries]) =>
    entries.map(([name, signature, description, example, min, max]) => ({
      name,
      category,
      signature,
      description,
      example,
      min,
      max,
    })),
);
export const formulaFunctionByName = new Map(
  formulaFunctions.map((entry) => [entry.name.toLowerCase(), entry]),
);
