// Symbols from the icon library, stored as "icon:<Name>:<#colour>".
export const iconColors = [
  ["Grau", "#646c79"],
  ["Blau", "#337ea9"],
  ["Grün", "#448361"],
  ["Gelb", "#cb912f"],
  ["Orange", "#d9730d"],
  ["Rot", "#d44c47"],
  ["Pink", "#c14c8a"],
  ["Lila", "#9065b0"],
  ["Braun", "#9f6b53"],
  ["Schwarz", "#282d36"],
] as const;
// German search words for each symbol.
export const iconLibrary: Record<string, string> = {
  House: "haus start",
  Briefcase: "arbeit projekt",
  Rocket: "rakete start",
  Lightbulb: "idee",
  Star: "stern favorit",
  Heart: "herz",
  Flag: "flagge ziel",
  Target: "ziel",
  Trophy: "pokal erfolg",
  Calendar: "kalender termin",
  Clock: "uhr zeit",
  Bell: "glocke hinweis",
  Book: "buch",
  BookOpen: "buch wiki",
  Notebook: "notizbuch",
  NotePencil: "notiz",
  FileText: "dokument datei",
  Folder: "ordner",
  Archive: "archiv",
  Tag: "etikett",
  Bookmark: "lesezeichen",
  CheckCircle: "erledigt aufgabe",
  ListChecks: "checkliste aufgaben",
  Kanban: "board",
  ChartBar: "diagramm",
  ChartLine: "diagramm verlauf",
  ChartPie: "diagramm",
  Table: "tabelle",
  Database: "datenbank",
  Code: "code",
  Terminal: "konsole",
  Bug: "fehler",
  Gear: "einstellungen",
  Wrench: "werkzeug",
  Hammer: "werkzeug",
  Lock: "schloss privat",
  Key: "schlüssel",
  Shield: "schutz sicherheit",
  Users: "team gruppe",
  User: "person",
  UserCircle: "profil",
  ChatCircle: "chat",
  Envelope: "mail",
  Phone: "telefon",
  Globe: "welt web",
  MapPin: "ort karte",
  Airplane: "flug reise",
  Car: "auto",
  Train: "zug",
  Coffee: "kaffee",
  Pizza: "essen",
  ShoppingCart: "einkauf",
  CreditCard: "karte zahlung",
  Money: "geld",
  Bank: "bank",
  Receipt: "beleg rechnung",
  Gift: "geschenk",
  Camera: "kamera foto",
  Image: "bild",
  MusicNote: "musik",
  FilmSlate: "film",
  GameController: "spiel",
  PaintBrush: "pinsel design",
  Palette: "farben design",
  PencilSimple: "stift",
  Sparkle: "funkeln",
  Sun: "sonne",
  Moon: "mond",
  Cloud: "wolke",
  Leaf: "blatt",
  Tree: "baum",
  Flower: "blume",
  Fire: "feuer",
  Lightning: "blitz",
  Atom: "atom wissenschaft",
  Flask: "labor",
  GraduationCap: "studium",
  Student: "schule",
  Buildings: "firma gebäude",
  Storefront: "laden",
  Handshake: "partner",
  Megaphone: "ankündigung",
  Newspaper: "news zeitung",
  Question: "frage",
  Info: "info",
  Warning: "warnung",
  Compass: "kompass",
  Cube: "würfel produkt",
  Plant: "pflanze",
  Package: "paket",
  Wallet: "geldbörse",
  Stethoscope: "gesundheit",
  Barbell: "sport",
};
const VALUE = /^icon:([A-Za-z]+):(#[0-9a-f]{6})$/;
export function parseLibraryIcon(value: string | null | undefined) {
  const m = VALUE.exec(value || "");
  if (!m || !(m[1] in iconLibrary)) return null;
  if (!iconColors.some(([, c]) => c === m[2])) return null;
  return { name: m[1], color: m[2] };
}
export const libraryIconValue = (name: string, color: string) =>
  `icon:${name}:${color}`;
